stages:
  - set-version
  - build

set-version:
  stage: set-version
  script:
    - dayOfYear=$(date +%j)
    - hour=$(date +%H)
    - minutes=$(date +%M)
    - seconds=$(date +%S)
    - year=$(date +%y)
    - echo "$(date +'%Y.%m.%d').$CI_JOB_ID" >> version.txt
  artifacts:
    paths:
      [ version.txt ]
 
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - VERSION_NUMBER=$(cat version.txt) 
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY_USER/octopublite-api:$VERSION_NUMBER -f ./api/Dockerfile ./api
    - docker push $DOCKER_REGISTRY_USER/octopublite-api:$VERSION_NUMBER
